# Example configuration for Helm chart db-backup

# Set environment variables to share S3
# config across multiple destinations 
env: {}
  # S3_BUCKET: ****
  # S3_ENDPOINT: ****
  # S3_ACCESS_KEY_ID: ****
  # S3_SECRET_ACCESS_KEY: ****

# The backups to perform
backups:
  timeout: 600
  loglevel: info
  rootdir: my_database_backups
  #google_chat:
  #  url: https://chat.googleapis.com/v1/spaces/XXX/messages?key=XXX
  #  loglevel: WARNING
  backups:
    backup_s3:
      source:
        type: mysql
        host: db01.example.com
        user: read_only
        password: SECRET
        databases:
        - my_database_01
        - my_database_02
      destination:
        type: s3
        access_key_id: SECRET
        bucket: my_bucket
        endpoint: some.endpoint.example.org
        secret_access_key: SECRET

# When to perform the backups
cronjob:
  schedule: "0/5 * * * *"
